### ISSUE TITLE
Write User Manual (documentation)

### ISSUE THREAD

**Issue by algorithmike** [CSUMB-SP17-CST499/group-assignment-tool#138]

**Comment by algorithmike** [comment]
The user manual is located here:
https://docs.google.com/document/d/1DDKlwWCnT0Ghuw9k58ZRWj56c5i6Rmt-CMG_HFP-36U/edit#

**Comment by algorithmike** [comment]
Completed draft of user manual. Requesting reviews @eliasargandara @ysosensk:
https://docs.google.com/document/d/1DDKlwWCnT0Ghuw9k58ZRWj56c5i6Rmt-CMG_HFP-36U/edit

**Comment by ysosensk** [comment]
Looks like I don't have permissions to access this document

**Comment by algorithmike** [comment]
@ysosensk Permissions updated. I believe it should be working now?

**Comment by ysosensk** [comment]
Done
