### ISSUE TITLE
Collect information and resources for implementation of Slack. (Document)

### ISSUE THREAD

**Issue by algorithmike** [CSUMB-SP17-CST499/group-assignment-tool#5]

**Comment by algorithmike** [comment]
Links found. Document in group Google drive, "Slack implementation." Slack seems like it will be easy to implement.

**Comment by algorithmike** [comment]
Links found. Document in group Google drive, "Slack implementation." Slack seems like it will be easy to implement.

**Comment by algorithmike** [comment]
Links found. Document in group Google drive, "Slack implementation." Slack seems like it will be easy to implement.

**Comment by ysosensk** [comment]
Could you provide the link to the document?

**Comment by algorithmike** [comment]
@ysosensk 
Here is the link:
https://docs.google.com/document/d/1-7kvLXr1sPImCWlYRNaROKPR-3xGEX_KcBVq4kFJCEk/edit?usp=sharing

**Comment by ysosensk** [comment]
@algorithmike Looks like I don't have access rights to this document (or the entire Google directory). Could you, please, add me - as  ysosensk@gmail.com?

**Comment by algorithmike** [comment]
Updated. Are you able to access now?

@ysosensk

**Comment by ysosensk** [comment]
Yes! @algorithmike
