### ISSUE TITLE
Create methods for the Bugzilla API

### ISSUE THREAD

**Issue by eliasargandara** [CSUMB-SP17-CST499/group-assignment-tool#66]
We need to create methods for retrieving groups from Bugzilla and updating who belongs to the groups.

**Comment by eliasargandara** [comment]
Our Bugzilla server's REST API can be queried using this URL:
- http://www.fruitfuldevelopment.com/bugzilla/rest.cgi/version

Here's the documentation on how to use the Bugzilla REST API: 
- https://bugzilla.readthedocs.io/en/5.0/api/index.html

**Comment by algorithmike** [comment]
@eliasargandara my functions say that I need to log in to do anything.

**Comment by algorithmike** [comment]
Bugzilla API incompatible with Python due to strict references, and can't currently be used with our server.
